name: FDS - Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    # Allows manual triggering of the workflow

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pylint
      run: |
        scripts/run_pylint.sh

  test:
    runs-on: ubuntu-latest

    needs:
      - lint

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov

    - name: Set up environment variables
      run: |
        echo "ISS_URL=http://localhost:8000" >> $GITHUB_ENV

    - name: Run tests
      run: |
        python -m pytest -v

    - name: Run tests with coverage report
      run: |
        python -m pytest --cov=fds --cov-report=xml --cov-report=term

    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

    - name: Validate test documentation
      run: |
        if [ ! -f "test/TEST_README.md" ]; then
          echo "Test documentation (TEST_README.md) is missing!"
          exit 1
        fi
